# fly.toml app configuration file generated for task-tracker-plus on 2023-06-13T08:22:14+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "task-tracker-plus"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
